name: CRM-Frontend-Deployment
on:
    workflow_run:
        workflows: ["Packages-Build"]
        types:
            - completed
jobs:
    auto-deploy:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'dev'

        runs-on: ubuntu-latest
        env:
            pm2_name: "ps-crm-fr"
            project_dir: "/home/${{ secrets.USERNAME }}/htdocs/pridespaces/monorepo"
            script-name: "build"

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Connect to server and clone pull repo
            - name: Handle server connection
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      echo "SSH actions starting...🔰🔰🔰"
                      cd "${{env.project_dir}}" && echo "Moved to directory"
                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                      git fetch origin "${{github.ref_name}}" && git checkout "${{github.ref_name}}" && echo "Fetched latest changes ✅" || echo "Fetch latest changes failed ❌"
                      git pull origin "${{github.ref_name}}" && echo "Pulled latest ✅" || echo "Pull latest failed ❌"
                      chmod +x build-script.sh && echo "Build script executable set ✅" || echo "Failed to set build script executable ❌"
                      chmod +x script.sh && echo "Serve script executable set ✅" || echo "Failed to set serve script executable ❌"
                      npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
                      npm run build -- --filter=ps-crm && echo "Build files ✅" || echo "NPM Build failed ❌"
                      cd "apps/ps-crm" && echo "Moved to ps-crm directory"
                      pm2 startOrRestart pm2.json && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
                      echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                      echo "SSH actions Ended ✅"
