name: Packages-Build
on:
    push:
        branches:
            - dev
jobs:
    auto-deploy:
        runs-on: ubuntu-latest
        env:
            project_dir: "/home/${{ secrets.USERNAME }}/htdocs/pridespaces/monorepo"

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Install dependencies and build
            # - name: Setting Up Node JS
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: "22.x"
            # - name: Installing node dependencies
            #   run: npm i
            # - name: Building TS -> JS
            #   run: npm run build

            # SFTP using milanmk actions
            # - name: SFTP build files transfer
            #   uses: milanmk/actions-file-deployer@master
            #   with:
            #     remote-protocol: "sftp"
            #     remote-host: ${{ secrets.HOST }}
            #     remote-user: ${{ secrets.USERNAME }}
            #     remote-password: ${{ secrets.PASSWORD }}
            #     remote-path: "${{env.project_dir}}"
            #     sync-delta-excludes: "dist/*"
            #     sync: full # full for all files transfer and delta for only changed

            # Connect to server and clone pull repo
            - name: Handle server connection
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      echo "SSH actions starting...🔰🔰🔰"
                      cd "${{env.project_dir}}" && echo "Moved to directory"
                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                      git checkout "${{github.ref_name}}" && echo "Checked out branch ✅" || echo "Checkout failed ❌"
                      git pull origin "${{github.ref_name}}" && echo "Pulled latest ✅" || echo "Pull latest failed ❌"
                      npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
                      npm run build -- --filter=@pride-spaces/backend && echo "Build backend packages files ✅" || echo "Backend packages build failed ❌"
                      npm run build -- --filter=@pride-spaces/common && echo "Build common packages files ✅" || echo "Common packages build failed ❌"
                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                      git stash clear && echo "Stashed changes cleared ✅" || echo "Stash clear failed ❌"
                      echo "SSH actions Ended ✅"
